name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on semantic version tags like v1.0.0

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -C ./src -o ./dist/wrapper-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: src/dist/wrapper-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
